Swift 3.1
outware/Scenarios pull request #33
Opened 2017-05-17 03:58 UTC by wisolith

Migrate to Swift 3.1

2017-05-19 01:48 UTC, gavanchan-outware requested changes
Looks good! Let me know what you think, and let's get this through! 🙂

2017-05-19 01:48 UTC, gavanchan-outware commented on Scenarios/StepArguments.swift
> +    return i + 1
Following the implementation of 'subscript', I would prefer forwarding this call to the underlying 'captures' collection, to retain the collection's semantics. Is this explicitly `i + 1`?

2017-05-19 01:55 UTC, gavanchan-outware requested changes
Beyond the codebase:

- Travis seems to be using an outdated version of Xcode. The Travis YAML file will need to be updated to use the required version of Xcode.
- This branch is out-of-sync with the latest branch on the main repository. Could you attempt a sync with the main repository?
- Nimble v7.0.0 does not behave as expected, in some cases. Do you feel that it would be good to revert to using the previous major version?

2017-05-19 04:13 UTC, wisolith commented on Scenarios/StepArguments.swift
> +    return i + 1
Something like `return captures.index(after: i)`?

2017-05-19 04:54 UTC, wisolith commented
- Updated `.travis.yml` to Xcode 8.3
- Rebased onto the current `master` of `outware/Scenarios`
- Set Nimble version to `5.1`

2017-05-19 05:47 UTC, gavanchan-outware commented on Scenarios/StepArguments.swift
> +    return i + 1
Yeah, if the implementation isn't meant to be explicitly `i + 1`, I think that would be more representative of the type.

2017-05-25 04:50 UTC, gavanchan-outware approved these changes

2017-05-25 06:34 UTC, gavanchan-outware commented
Looks good! Passes on Travis and when run on my local machine using Xcode 8.3.

Thanks for that, @wisolith!

Time to merge!

2017-05-25 06:34 UTC, merged